Name:
 My Workflow 
   on: repository_dispatch: types: [my_event_type] 
jobs: 
    build: runs-on: 
            ubuntu-latest  
    steps:  
       - name: Checkout code                   
           uses: actions/checkout@v2 # Run your automation framework here 
      - name: Run my automation framework 
           run: ./my-framework.sh
