# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on: 
  repository_dispatch: 
    types: [my_event_type] 
    
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

   runs-on: ubuntu-latest

   steps:  
     - name: Checkout code                   
       uses: actions/checkout@v3.2.0 # Run your automation framework here 
     - name: Run my automation framework 
       run: ./my-framework.sh
